"""empty message

Revision ID: 5337c0eb33c6
Revises: c47d4eba4868
Create Date: 2021-01-13 17:23:40.747654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5337c0eb33c6'
down_revision = 'c47d4eba4868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genre', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'genre')
    # ### end Alembic commands ###
